### PR TITLE
Add demo to the Readme

### PR DESCRIPTION
**Pull request by RoneoOrg**

### CODE REVIEW

**Comment by RoneoOrg** [comment]
Merging this minor update pending for a week

**Comment by henryiii** [comment]
Why not put this in GHA + GH Pages? Then the building code is public. I'd be happy to [set that up](https://scikit-hep.org/developer/gha_basic#github-pages), but it does need @halogenica to turn on the new publish to GH Pages setting in settings -> pages.

(I"m not very available till after next week though; teaching a class and speaking at two overlapping workshops).

**Comment by RoneoOrg** [comment]
> Why not put this in GHA + GH Pages? Then the building code is public. I'd be happy to [set that up](https://scikit-hep.org/developer/gha_basic#github-pages), but it does need @halogenica to turn on the new publish to GH Pages setting in settings -> pages.

Indeed I do not have access to the Pages settings, let's wait for halogenica

**Comment by RoneoOrg** [comment]
> Why not put this in GHA + GH Pages? Then the building code is public.

Another advantage: now the build is done from a separate repo, which I have to sync manually. Using a build right from this repo would ease the process

**Comment by halogenica** [comment]
Hey @henryiii @RoneoOrg this GHA is new to me. I just enabled it and the demo site is being served here: https://halogenica.github.io/beautifulhugo/ (which redirects to halogenica.net/beautifulhugo, but it's probably best to use https://halogenica.github.io/beautifulhugo/ when linking elsewhere in case I change my custom domain name at some point). I don't know how to set up the GH Action to actually run Hugo, is that something you can configure now that I've enabled the Pages functionality? Thank you so much for working on this and let me know if you need me to do anything else!

**Comment by henryiii** [comment]
Sure, I can set it up. In fact, Hugo is one of the [starter workflows](https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml). :) Did you turn on the Actions source for Pages?

[Pages selector](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/)

**Pull request merged**
