### PR TITLE
Allow codeblocks to be scrollable

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Review by domenkozar — COMMENTED** [review]
Enable only horizontal scrollbar

**Comment by domenkozar** [comment]
You can see this on action by opening https://blog.cachix.org/posts/2022-07-29-cachix-deploy-public-beta/ on your mobile device.

**Review by JonasVautherin — APPROVED** [review]
Agreed, I'm taking this in my fork!

Thanks! :pray:

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
I'd noticed this, but hadn't looked into it yet! Thank you!

**Pull request merged**
