### PR TITLE
Add chroma highlighting support (Hugo now use it)

### PR DESCRIPTION
**Pull request by badele**

### CODE REVIEW

**Comment by henryiii** [comment]
I was just about to make this change and make a PR! Thanks! 👍

**Comment by henryiii** [comment]
I've made a few improvements, such as a note in the README on activating Chroma support in the theme (it's default in Hugo!) and theming. I removed the highlight JS (not just the CSS) when Chroma is activated, and am using the same name for the css file as in the docs. The only comment I might suggest is a better default; the monokai theme is ugly (IMO) and doesn't match the normal default for this theme. I'm locally using manni for now.

For the moment, @badele , I'll make the PR to your branch.

**Comment by badele** [comment]
Thank @henryiii for you PR :)

**Comment by halogenica** [comment]
Thank you both very much! I also wanted to add this, I appreciate your PR :)

**Pull request merged**
