### PR TITLE
Add about social icon

### PR DESCRIPTION
**Pull request by xuhdev**
This gives the website author some flexibility to put a link to biograph.

### CODE REVIEW

**Comment by ibnunowshad** [comment]
Do you have some screenshot of this change for `fas fa-at`?

**Comment by xuhdev** [comment]
Yes, check out a live example at https://hugo-apt.8hob.io/

**Comment by ibnunowshad** [comment]
> Yes, check out a live example at https://hugo-apt.8hob.io/

It is more like a `@` for email. But I may use it for email instead of `About`

**Comment by xuhdev** [comment]
I simply followed fontawesome's decision... I personally also got the impression of @ being "about". @ is not only used in email, but also indicating one's host generally (think about ssh, ftp). Today also used for pinging someone like how it is used on GitHub.

**Pull request merged**
