### PR TITLE
Enable i18n

### PR DESCRIPTION
**Pull request by rayjolt**
Enable i18n and add translations in English and Japanese. See #44 for more details.

### CODE REVIEW

**Comment by halogenica** [comment]
Fantastic, thank you very much for the welcome addition!

**Comment by mithuns** [comment]
I know this has been long closed, but can we please add more documentation in the repo's Readme.md as to how to use the multi-language feature while consuming this theme. 
Like between keeping file names with ```.en``` or ```.de``` VS making folder names with those language codes and how to organize everything. 
If @halogenica thinks it would be better for me to open a new issue , please let me know I can do that. Also, attach , what I have done to try to make the folder based approach work and the challenges I am facing.
Thanks

**Comment by rayjolt** [comment]
mithuns: Check out https://github.com/rayjolt/hugo-multilingual-example for a sample configuration. The guide at https://regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/ also looks pretty good. As for adding info to the readme, the folder structure and the settings for multilingual sites are common across all themes, so it might be better to link to the Hugo docs instead of making our own guide which might go out of date.

**Comment by mithuns** [comment]
Thank you for replying @rayjolt , I will take a look at let you know how it goes. Thanks.

**Pull request merged**
