### PR TITLE
multiple improvements

### PR DESCRIPTION
**Pull request by pad92**
# Changelog

- Add : SEO structured data
- Upgrade Font Awesome to v5
  - Add : docker into footer
- Add : Table of contents
- Add : Archives page ( from [Even theme](https://themes.gohugo.io/hugo-theme-even/) )
- Rewrite page header and footer
- Use post logo for top images
- Change 404 template ( remove image )
- Add related post
- Remove CDN `js/css` use local `/static/`
- Add reveal ( from [reveal-hugo](https://themes.gohugo.io/reveal-hugo/) )
- Added support for mermaid diagrams from #193
- Ability to disable KaTex and Photoswipe ( site or post param ) #195

### CODE REVIEW

**Comment by pad92** [comment]
@halogenica i cancel my pull and keep my fork ? :(

**Comment by halogenica** [comment]
Hey @pad92 , thank you for making so many updates to beautiful hugo! I've been working this weekend to get through the issues and PRs, as well as launch a site. As you can see, this is an extremely large PR and It will take me some time to review all of the code, but I'd love to pull in your great new additions.

**Comment by pad92** [comment]
oups ...

**Comment by halogenica** [comment]
Did you mean to close this? I'm still happy to take many of your changes. I've been going through them to separate out each change. 

I'd love to take your changes in the future too. Would you mind separating them into individual PR's for each feature next time? Thanks!

**Comment by pad92** [comment]
I will update PR from my master branch

**Comment by halogenica** [comment]
I have started integrating these changes. I am integrating piece by piece because there are some formatting changes and config changes that I did not want to check in. I would like to add all the features and fixes you've created, but I don't know how to selectively merge them since everything is in a single PR. I'll continue going through this PR to add these features, and you may want to keep your branch with your personal config changes and preferences. I'll let you know when I'm finished, and If I miss something that you think should have gone into the theme then please make another PR :) 

This is still a work in progress.

**Comment by halogenica** [comment]
I've just made what I think are the majority of the changes in this PR. I would still like to add the TOC feature you made. Thank you again for the changes! If there are features I'm missing, can you add them to separate PRs?

**Comment by pad92** [comment]
ok, and sorry for this huge PR

**Comment by halogenica** [comment]
No problem and thanks again! I'm going to close this PR. I'd love to merge in the TOC changes and any other SEO updates I may have missed or butchered; so please feel free to submit more PRs :)

**Comment by pad92** [comment]
@halogenica  I PR from pad92/beautifulhugo/beautifulhugo or from fresh fork of halogenica/beautifulhugo/master ?

**Comment by halogenica** [comment]
From 'halogenica/beautifulhugo/master' please. Thank you!

**Comment by pad92** [comment]
I do some cleanup on [my fork](https://git.depad.fr/github/beautifulhugo) from upstream, if someone want to merge feature by feature ... :)

- use only local static ( no cdn )
- custom logo on post header
- #243 
- #226
- #225

**Pull request closed without merging**
