### PR TITLE
Added support for bigimg(s) on front page

### PR DESCRIPTION
**Pull request by liwenyip**
This is a feature in Beautiful Jekyll, see front page of http://deanattali.com/
Addresses issue #14

### CODE REVIEW

**Comment by liwenyip** [comment]
Demo at http://www.liwen.id.au/

**Comment by halogenica** [comment]
Checked in the unrelated changes from this pull request: 0338abd814908fc79ab110c819d72d827d4fcc1e, 43fd0bb8bd2044efeb0cf9153f30a6bbec70717a, 867ae67b525de6c7dc979138ab6027e27bac869f, and d3ebf37be4b8974837dc62c0f0b61febc6a6c5fe.

I intend to also merge the bigimg support, however I want to make sure the implementation is consistent on both the front page and other pages/posts.

Please do not pile on additional changes to this pull request unrelated to the bigimg support. I'm happy to accept additional pull requests.

**Comment by halogenica** [comment]
Added bigimg functionality equivalent to this pull request, as well as support for multiple bigimg's in regular pages/posts, and added samples. Please see commit f84ba895a89c8c923fa62fa02528ba69741ff427.

This pull request is now completely resolved. Thank you for the PR!

**Comment by liwenyip** [comment]
> Please do not pile on additional changes to this pull request unrelated to the bigimg support.

Sorry about that, it's because I build my website using my master branch (I have a git post-receive hook on my webserver that pulls the latest liwenyip/beautifulhugo master directly from GitHub and runs hugo).

I know for next time to create a separate branch for pull requests.

**Comment by halogenica** [comment]
No worries! It's all sorted out now and all your changes have been committed. And I really appreciate all help :)

**Comment by halogenica** [comment]
Speaking of which, the next thing I wanted to add to the theme was photoswipe, and I saw on your github that you've already done it! I've played around with the Hugo Photoswipe Scripts but it doesn't quite work the way I want it to. When you're happy with the implementation I'd love to merge it into the theme.

**Pull request closed without merging**
