### PR TITLE
Make all full-page templates inherit from a block template

### PR DESCRIPTION
**Pull request by rayjolt**
See the first commit for the rationale for this change. The diff from the first commit is also easier to read than the one for the pull request as a whole.

### CODE REVIEW

**Comment by rayjolt** [comment]
I'll rebase this later on.

**Comment by rayjolt** [comment]
Rebased again.

**Comment by halogenica** [comment]
Thank you again very much!

**Comment by rayjolt** [comment]
You're welcome. Thanks for the merge!

**Pull request merged**
