### PR TITLE
Add nested element to the main menu of the exampleSite.

### PR DESCRIPTION
**Pull request by 1138-4EB**

### CODE REVIEW

**Comment by halogenica** [comment]
Thanks again for the PR. I wanted to make sure the pages linked by the nested menu actually existed, so I made a slightly different change that still shows a nested menu, but links to some of the existing posts.

**Comment by 1138-4EB** [comment]
Are you sure pushed the proper branch to GitHub? I cannot find such a modification in any of the last six commits (938766F to 46de23e). If I missed it, I'd thank you to point me there.

**Comment by halogenica** [comment]
Thanks for letting me know! I did forget to sync :) The change I was referring to should be pushed back now, 393582a537809d0b676f2ad8b748efc069937fa2

**Comment by 1138-4EB** [comment]
It's OK now. Thanks!

**Pull request closed without merging**
