### PR TITLE
[Feature] Archives

### PR DESCRIPTION
**Pull request by pad92**
add archive page for #220

### CODE REVIEW

**Comment by VincentTam** [comment]
I've tested this PR on my demo Hugo GitLab pages with comment reply at https://vincenttam.gitlab.io/bhdemo ([source](https://gitlab.com/vincenttam/bhdemo)), which is created to test #222 

This works great!  Thank you @pad92 for your contributions.

archive

**Comment by pad92** [comment]
thx, it´s from even archive theme too

Le mer. 21 nov. 2018 à 12:57, Vincent Tam <notifications@github.com> a
écrit :

**Comment by VincentTam** [comment]
Due to #261, we should replace _deprecated_ `{{ .URL }}` with `{{ .RelPermalink }}`.

```diff
diff --git a/layouts/_default/section.html b/layouts/_default/section.html
index 6844096..3057cf1 100644
--- a/layouts/_default/section.html
+++ b/layouts/_default/section.html
@@ -34,7 +34,7 @@
                           {{ $element.Date.Format "01-02" }}
                       </span>
                       <span class="archive-post-title">
-                          <a href="{{ $element.RelPermalink }}" class="archive-post-link">
+                          <a href="{{ $element.URL }}" class="archive-post-link">
                               {{ .Title }}
                           </a>
                       </span>
@@ -46,12 +46,12 @@
           <ul class="pager main-pager">
             {{ if .Paginator.HasPrev }}
               <li class="previous">
-                <a href="{{ .RelPermalink }}page/{{ .Paginator.Prev.PageNumber }}/">&larr; {{ i18n "newerPosts" }}</a>
+                <a href="{{ .URL }}page/{{ .Paginator.Prev.PageNumber }}/">&larr; {{ i18n "newerPosts" }}</a>
               </li>
             {{ end }}
             {{ if .Paginator.HasNext }}
               <li class="next">
-                <a href="{{ .RelPermalink }}page/{{ .Paginator.Next.PageNumber }}/">{{ i18n "olderPosts" }} &rarr;</a>
+                <a href="{{ .URL }}page/{{ .Paginator.Next.PageNumber }}/">{{ i18n "olderPosts" }} &rarr;</a>
               </li>
             {{ end }}
           </ul>
```

**Comment by halogenica** [comment]
Awesome stuff, thank you so much for this feature!

**Comment by milosgajdos** [comment]
Are you still thinking of bringing this back or have you now completely discarded the idea?

**Pull request merged**
