### PR TITLE
add social network share links

### PR DESCRIPTION
**Pull request by jms**

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
This is great! @halogenica any chance we could have this merged?

**Comment by hukacode** [comment]
There is one wrong type, Pintrest should be Pinterest.

**Comment by dancwilliams** [comment]
Running this on my site ([`https://networkhobo.com`](https://networkhobo.com)) and it works great!  Thanks for the contribution!

**Comment by johanbrandhorst** [comment]
On second thought, I actually think this could do with some more configuration options. I made a some custom sharing buttons with the use of https://sharingbuttons.io/ and it was extremely easy to integrate, so I think it should be possible to create a partial that allows customization beyond these.

**Comment by halogenica** [comment]
Wonderful addition, thank you very much!

**Pull request merged**
