### PR TITLE
Use hand written summary and make link to read rest

### PR DESCRIPTION
**Pull request by hsn10**
Fix for #426

### CODE REVIEW

**Review by JonasVautherin — APPROVED** [review]
Works for me :+1:

**Comment by JonasVautherin** [comment]
Since @henryiii is active now, I'd like to ping on this one.

To me it really fixes the bug, otherwise the home page does not render correctly (both the summary and the page are rendered together, instead of only the summary)

**Comment by danielwagn3r** [comment]
Is there any plan to merge this? Summaries with Hugo have some problems in general, i.e. when it comes to images, code-snippets, ..., and [Front Matter Summary](https://gohugo.io/content-management/summaries/#front-matter-summary) is for sure a way to help out.

**Comment by henryiii** [comment]
This looks reasonable. Feel free to ping, I'll try to spend some time on this in the future, but have a long list of things to finish first. :)

**Pull request merged**
